modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="All rights reserved"
issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="coalstone" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Coalstone" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/coalstone/" #optional
logoFile="coalstone_logo.png" #optional
authors="Kim Royal" #optional
description='''
Coalstone is a mod that adds a new resource created with coal and cobblestone.

Coalstone can be used to create decoration blocks, tools, and improved methods of Vanilla-inspired processing.
'''
[[dependencies.coalstone]] #optional
	modId="forge" #mandatory
	mandatory=true #mandatory
	versionRange="[35,)" #mandatory

[[dependencies.coalstone]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"

[[dependencies.coalstone]]
    modId="patchouli"
    mandatory=false
    versionRange="[1.16.4-48,)"

[[dependencies.coalstone]]
    modId="jei"
    mandatory=false
    versionRange="[7.6.0.58,)"


